### ISSUE TITLE
Enable possibility to set static IP

### ISSUE THREAD

**Issue by skatun** [ThomDietrich/openhabian#23]
I know several people(most?) like to set static IP of their pi, so that they dont need to fuzz around in their router settings todo so.  This can be achieved by alternating: sudo vi /etc/network/interfaces

```
 # The loopback interface
 auto lo
 iface lo inet loopback
 auto eth0
 iface eth0 inet static
 #your static IP
 address 192.168.1.118  
 #your gateway IP
 gateway 192.168.1.1
 netmask 255.255.255.0
 #your network address "family"
 network 192.168.1.0
 broadcast 192.168.1.255
```

**Comment by ThomDietrich** [comment]
Hey, yes that's possible.
Are you asking to add this option to the openHABian menu?

I would actually not encourage a user to do this. Static IPs are inferior to a configured DHCP server. First off, you can always reach your device by using the hostname "openhabianpi.local" instead of an IP. Furthermore you are able to fix the DHCP-assigned IP of the device in your router settings. Yes, you'll have to "fuzz around" in your router settings, but hey, that's what they are for... I like this second option as your device will always listen on the same IP, even if you were to install a completely different OS. On the other hand you can move your device to a new network without having the problem of conflicting IP addresses or different subnets. That's a pain in the ass I'd rather never go back to.

**Comment by ThomDietrich** [comment]
This should now be possible, even before running the setup. You should be able to configure the ip settings you want directly after flashing the SD card on your PC:
https://github.com/ThomDietrich/openhabian/commit/db63b4a57632de75ea48f52a297808f378b1d2fb

Please comment as soon as you can confirm this to be working.
