### ISSUE TITLE
Further simplification of connecting to the openHAB/karaf console. 

### ISSUE THREAD

**Issue by BClark09** [ThomDietrich/openhabian#25]
With Debian, you can place the following inside .ssh/config

```
Host openhab
HostName localhost
User openhab
Port 8101
```

and then you'd be able to connect to the karaf console without having to remember the port number or specific syntax.

```bash
ssh openhab
```

Since this image is all for simplifying the use and setup of openHAB, would you think this is a good addition to have?

**Comment by ThomDietrich** [comment]
What do you think about [this])https://github.com/ThomDietrich/openhabian/blob/master/includes/bash_profile#L13)?

**Comment by BClark09** [comment]
Whoops! I hadn't realised that there was the alias there! :see_no_evil: 

Regarding the second link, do you think there should be a warning regarding opening up the console to external connections? It doesn't sound like a very safe thing to give people who will keep default settings.

**Comment by ThomDietrich** [comment]
The alias has a problem thou. It is not quite reliable at first.
I didn't fully investigate but I already discussed this somewhere: The system needs to calculate the SSH host key. This key will be generated upon first ssh connection attempt. The key size is set to 4096. On a RPi this takes a long time, longer than the ssh timeout, leading to a failure of the first connection attempt.
The alias is connection locally and seems to not succeed without at least one successful ssh connection.
This should be further investigated and solved by either creating the key on package installation and/or reducing the key size. I will look into it some point after this weekend.

Regarding the opening of the console: I'm torn about this topic. With 90% of the users having their RPi on a local subnet and the default sudo-enabled pi:raspberry login, the default password of the karaf console is not worth much.
But yes you are right. It would be the wise choice to print out a warning and at the same time prompt for an alternative password. At the same time we should remind them that they should change their pi user password.

Agreed?

**Comment by ThomDietrich** [comment]
Ah, also regarding the alias, there is [more](https://github.com/ThomDietrich/openhabian/blob/master/includes/bash.bashrc#L76-L94). I'm still sorting out which are really useful to the enduser and will describe them in the documentation which I'll create hopefully soon.

**Comment by BClark09** [comment]
Right, I did actually come into the time-out problem but on second attempt it worked fine. I hadn't considered that the key is generated on first ssh attempt.

The karaf console suffers from a major security flaw, and this can be exploited in openHABian if it's opened to the public (I haven't found the best way to fix this yet, but I can still connect remotely to my openHAB console without a password from any computer, which worries me.). This is particularly dangerous because you can execute some system commands with "exec". My argument would be to not give the user an easy option to bind to all interfaces at all, but to make it as simple as possible to open the console once you have "ssh"ed into your RPi, (which *can* be made fairly secure).

1. ssh-keygen
2. copy generated public key from /home/pi/.ssh/id_rsa.pub to keys.properties
3. Add config to .ssh/config
4. Unfortunately 2 needs to be repeated for each update since there's no user config file for openHAB's karaf console.

**Comment by ThomDietrich** [comment]
"I can still connect remotely to my openHAB console without a password" ?? That can't be right. The default login is openhab:habopen and this can be changed.

I think opening the console to the public AND securing it is the right choice. Having to "tunnel" a connection is neither user friendly nor meaningful if the security is implemented *right* . I guess you know that best as tunneling the openHAB web interface through a proxy was the only option to provide security -.-

The generation of the host key should rather be part of the apt installation process. Therefor a method should be added [here](https://github.com/openhab/openhab-distro/tree/master/distributions/distribution-resources/src/main/resources/deb/control-runtime) and theoweiss should sign off on that. I'm not tagging him right now because it's too early

**Comment by BClark09** [comment]
I'm with you now, I hadn't considered changing the password so got myself into confusion. Sorry about that! I completely agree that's the best way to go, as long as you make sure that the username/password can't be set to openhab:habopen if sshHost=0.0.0.0

**Comment by ThomDietrich** [comment]
To summarize:

1. Extend the menu option to open the console by a prompt to set the password (I would still leave habopen as a default)

2. Investigate into the alleged ssh key problem:

I just had the chance to try a few things on a new installation but was surprised to see everything working. No timeouts on either `karafshell` and `ssh openhab@localhost -p 8101`. My first `karafshell` just needed a few seconds to go through. The reason seems to be quite simple: my testing system was a RPi 1 B+ and this time I am on a RPi3, powerful to calculate the ssh key before the timeout.

So the question is: Do we need to do anything here or can we just tell users that they need 1-2 retries on first connection...?

**Comment by BClark09** [comment]
Yes that should be fine. I have also just tested this on both a RPi2 and an RPi3, the timeout occurred once out of three complete re-installs on the RPi2 (but a retry on that fail attempt worked), and not at all on the RPi3.

I would be tempted to say that we wouldn't need to do anything special here, I can't see it being a hindrance to the majority of your users. Do you know if there are many people using an RPi 1? I didn't think it would be able to cope with what openHAB threw at it sometimes.

**Comment by ThomDietrich** [comment]
Implemented in the last two commits.

![2016-10-29 16_41_07-sprungliste fur ssh telnet and rlogin client](https://cloud.githubusercontent.com/assets/2870104/19830370/b55c33e8-9df6-11e6-8849-f1b48cf654ab.png)

It's working as far as I can tell. I have implemented very weak input checking. Hope nobody will take harm from that :)
